version: '3.0'

services:
  db:
    network_mode: "host"
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'stockpymes'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  api:
    network_mode: "host"
    image: alexvegadev/stock_pymes_rs:latest
    container_name: api_sp
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - '8080:8080'
    expose:
      - '8080'
    environment:
      - DATABASE_URL=mysql://root:somepass@localhost:3306/stockpymes

volumes:
  my-db: