version: '3.0'

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=stockpymes
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_USER=alex
      - MYSQL_PASSWORD=example123
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /var/lib/mysql
    networks:
      - backend

  api:
    image: stock_pymes_rs_api:latest
    container_name: api_sp
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - '8080:8080'
    expose:
      - '8080'
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/stockpymes
    networks:
      - backend

networks:
  backend:
    driver: "bridge"