version: '3.0'

services:
  db:
    network_mode: "host"
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'stockpymes'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'stocker'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'somepass'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'somepass'
      # Access to every single host
      MYSQL_ROOT_HOST: '%'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  api:
    network_mode: "host"
    image: alexvegadev/stock_pymes_rs:latest
    container_name: api_sp
    restart: always
    depends_on:
      - db
    links:
      - db
    ports:
      - '8080:8080'
    expose:
      - '8080'
    environment:
      - DATABASE_URL=mysql://root:somepass@localhost:3306/stockpymes

volumes:
  my-db: